fighters = {
    1: "Itsa Me.... Mario!!",
    2: "Thicc monke",
    3: "Zelda, the person in green",
    4: "Samus... fake Mando",
    5: "Dark Samus... fake Samus",
    6: "barney is a dinosaur from Toad's Imagination....",
    7: "Poyo!",
    8: "Fawkes",
    9: "Lightning Rat",
    10: "Mario but tall and clumsy",
    11: "fuq ness",
    12: "Falcon Kick!",
    13: "cat-Poyo",
    14: "fruit princess",
    15: "flower girl",
    16: "i like tortlez",
    17: "No nana, No damage",
    18: "OMG itz the Princess!!!",
    19: "breh, its the princess",
    20: "why. when did mario get a phD",
    21: "Lightning Rat but small",
    22: "Ravioli with tech",
    23: "OG bad-hair",
    24: "Fake Marth",
    25: "Lonk but childe",
    26: "DORiah",
    27: "(m) Ewww 2",
    28: "fiyaaaa",
    29: "Google Chrom",
    30: "Literally 2D",
    31: "PTSD from Brawl",
    32: "heh pits",
    33: "oOh dark pits",
    34: "How does the hair fit in the helmet?",
    35: "yessir",
    36: "Bombs galore.",
    37: "Ight from fire emblem",
    38: "3 in 1!!!",
    39: "not Thicc monke ",
    40: "fuq lucass",
    41: "literally 1 special move",
    42: "beeg hamr",
    43: "servants? breh",
    44: "what doesnt kill me.... just makes me stronger",
    45: "B.O.T. ded xD",
    46: "Lonk but from Tom and Jerry",
    47: "Nick Furry",
    48: "plants trees. be like dis dood",
    49: "he thinks he's so cool, but he just looks stoopid",
    50: "Downward dog",
    51: "Luma",
    52: "#1 worst!!",
    53: "the green ninja",
    54: "laser staff",
    55: "Blinky's monster",
    56: "his sword can break",
    57: "Buster!",
    58: "tortle fun size",
    59: "the hell is a duck hunt",
    60: "seryusly",
    61: "hado",
    62: "Cloud Strife (he has a last name?!!)",
    63: "dafuq is that hair",
    64: "moon dance",
    65: "woomy on a chair",
    66: "get ridley of this character already",
    67: "belmont",
    68: "good belmont",
    69: "this dude is a king? he loses his crown too much",
    70: "mayor with mines",
    71: "STOP USING YOUR SIDE SPECIAL",
    72: "Mario's dead",
    73: "Loki = Tuxedo and knifes",
    74: "kamikaze",
    75: "more duck hunt?",
    76: "terryble",
    77: "heavy from FE?",
    78: "revolutionary ARMS",
    79: "Enderdude",
    80: "ripped chad. beeg sword. killed mario",
    81: "more anime swordfighters 2 pack!!",
    82: "frikin has everything",
    83: "bruhler",
    84: "rathalos in smash",
    85: "sans",
    86: "do whatever tbh",
}